apiVersion: apps/v1
kind: Deployment
metadata:
  name: ragna-app
spec:
  template:
    spec:
      containers:
      - name: ragna-frontend
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: NODE_ENV
          value: "development"
        - name: DEBUG
          value: "true" 