apiVersion: apps/v1
kind: Deployment
metadata:
  name: pragttle-backend
  namespace: pragttle
  labels:
    app: pragttle-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pragttle-backend
  template:
    metadata:
      labels:
        app: pragttle-backend
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: pragttle-backend
        image: ghcr.io/moi/pragttle-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:pragttle123@postgres-postgresql.pragttle.svc.cluster.local:5432/pragttle"
        - name: RUST_LOG
          value: "info"
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5 