apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pragttle

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment-backend.yaml
  - deployment-frontend.yaml
  - service-backend.yaml
  - service-frontend.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: pragttle
  app.kubernetes.io/part-of: pragttle 