apiVersion: apps/v1
kind: Deployment
metadata:
  name: ragna-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ragna
  template:
    metadata:
      labels:
        app: ragna
    spec:
      containers:
      - name: ragna-frontend
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5 