apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: pragttle-db
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 15.5.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      postgresPassword: "pragttle123"
      database: "pragttle"
    primary:
      persistence:
        enabled: true
        size: 8Gi
    service:
      type: ClusterIP 