apiVersion: apps/v1
kind: Deployment
metadata:
  name: ragna-app
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: ragna-frontend
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: NODE_ENV
          value: "production"
        - name: DEBUG
          value: "false" 