apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ragna-prod

namespace: ragna

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: ragna-app

configMapGenerator:
  - name: ragna-config
    behavior: merge
    literals:
      - ENVIRONMENT=production
      - DEBUG=false
      - LOG_LEVEL=info

commonLabels:
  environment: production 