apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: ragna-cluster
servers: 1
agents: 2
image: rancher/k3s:latest
ports:
  - port: 6550:6550
    nodeFilters:
      - server:0
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: "60s"
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true 