apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 13.2.26
    helm:
      values: |
        global:
          postgresql:
            auth:
              postgresPassword: "pragttle123"
              database: "pragttle"

        primary:
          service:
            type: ClusterIP
            port: 5432
          persistence:
            enabled: true
            size: 8Gi
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

        serviceAccount:
          create: true
          name: "postgres-postgresql"

        # Déployer dans le namespace pragttle
        namespaceOverride: "pragttle"
  destination:
    server: https://kubernetes.default.svc
    namespace: pragttle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 