apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pragttle
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/benoit-planche/Pragttle
    targetRevision: HEAD
    path: apps/pragttle
  destination:
    server: https://kubernetes.default.svc
    namespace: pragttle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10 