apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ragna
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/RAGNagna.git
    targetRevision: HEAD
    path: apps/ragna/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: ragna
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10 